site_name: Junhua Du Personal Wiki
nav:
    - Profile: index.md
    - 个人简介: index_zh.md
    - Postgraduate Experience: postgraduate_experience_en.md
    - 博士经历: postgraduate_experience_zh.md
    - Undergraduate Experience: undergraduate_experience_en.md
    - 本科经历: undergraduate_experience_zh.md
    - Research History: history_en.md
    - 研究历史: history_zh.md
theme:
    name: 'material'

