site_name: Junhua Du Personal Wiki (杜晋华 个人WIKI)
nav:
    - Profile (EN): index_en.md
    - 个人简介 (ZH): index_zh.md
    - Postgraduate Experience (EN): postgraduate_experience_en.md
    - 博士经历 (ZH): postgraduate_experience_zh.md
    - Undergraduate Experience (EN): undergraduate_experience_en.md
    - 本科经历 (ZH): undergraduate_experience_zh.md
    - Research History (EN): history_en.md
    - 研究历史 (ZH): history_zh.md
theme:
    name: 'material'

